// Generated by gencpp from file robot/compass.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGE_COMPASS_H
#define ROBOT_MESSAGE_COMPASS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot
{
template <class ContainerAllocator>
struct compass_
{
  typedef compass_<ContainerAllocator> Type;

  compass_()
    : header()
    , heading_deg(0.0)  {
    }
  compass_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , heading_deg(0.0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _heading_deg_type;
  _heading_deg_type heading_deg;




  typedef boost::shared_ptr< ::robot::compass_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::compass_<ContainerAllocator> const> ConstPtr;

}; // struct compass_

typedef ::robot::compass_<std::allocator<void> > compass;

typedef boost::shared_ptr< ::robot::compass > compassPtr;
typedef boost::shared_ptr< ::robot::compass const> compassConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot::compass_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot::compass_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'robot': ['/home/abeni/rob/src/robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot::compass_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot::compass_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot::compass_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::compass_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot::compass_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cf6fb6acd86d7f29e5238051c7a5ee6";
  }

  static const char* value(const ::robot::compass_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cf6fb6acd86d7f2ULL;
  static const uint64_t static_value2 = 0x9e5238051c7a5ee6ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot/compass";
  }

  static const char* value(const ::robot::compass_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot::compass_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 heading_deg\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robot::compass_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot::compass_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.heading_deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct compass_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::compass_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot::compass_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "heading_deg: ";
    Printer<float>::stream(s, indent + "  ", v.heading_deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_COMPASS_H
