// Generated by gencpp from file vision/targets.msg
// DO NOT EDIT!


#ifndef VISION_MESSAGE_TARGETS_H
#define VISION_MESSAGE_TARGETS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <vision/face_box.h>

namespace vision
{
template <class ContainerAllocator>
struct targets_
{
  typedef targets_<ContainerAllocator> Type;

  targets_()
    : faces()
    , ref_img_width(0)
    , ref_img_height(0)  {
    }
  targets_(const ContainerAllocator& _alloc)
    : faces(_alloc)
    , ref_img_width(0)
    , ref_img_height(0)  {
    }



   typedef std::vector< ::vision::face_box_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::vision::face_box_<ContainerAllocator> >::other >  _faces_type;
  _faces_type faces;

   typedef uint16_t _ref_img_width_type;
  _ref_img_width_type ref_img_width;

   typedef uint16_t _ref_img_height_type;
  _ref_img_height_type ref_img_height;




  typedef boost::shared_ptr< ::vision::targets_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision::targets_<ContainerAllocator> const> ConstPtr;

}; // struct targets_

typedef ::vision::targets_<std::allocator<void> > targets;

typedef boost::shared_ptr< ::vision::targets > targetsPtr;
typedef boost::shared_ptr< ::vision::targets const> targetsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision::targets_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision::targets_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'vision': ['/home/abeni/rob/src/vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision::targets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision::targets_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::targets_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision::targets_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::targets_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision::targets_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf92c07c6e3081a4a97a355ceda9b6aa";
  }

  static const char* value(const ::vision::targets_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf92c07c6e3081a4ULL;
  static const uint64_t static_value2 = 0xa97a355ceda9b6aaULL;
};

template<class ContainerAllocator>
struct DataType< ::vision::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision/targets";
  }

  static const char* value(const ::vision::targets_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision::targets_<ContainerAllocator> >
{
  static const char* value()
  {
    return "face_box[] faces\n\
uint16 ref_img_width\n\
uint16 ref_img_height\n\
\n\
================================================================================\n\
MSG: vision/face_box\n\
geometry_msgs/Point top_left\n\
geometry_msgs/Point width_height\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vision::targets_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision::targets_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.faces);
      stream.next(m.ref_img_width);
      stream.next(m.ref_img_height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct targets_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision::targets_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision::targets_<ContainerAllocator>& v)
  {
    s << indent << "faces[]" << std::endl;
    for (size_t i = 0; i < v.faces.size(); ++i)
    {
      s << indent << "  faces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::vision::face_box_<ContainerAllocator> >::stream(s, indent + "    ", v.faces[i]);
    }
    s << indent << "ref_img_width: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ref_img_width);
    s << indent << "ref_img_height: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ref_img_height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_MESSAGE_TARGETS_H
