"""autogenerated by genpy from vision/face_box.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class face_box(genpy.Message):
  _md5sum = "9bdccc133bdc2e2db906756187d7a6f5"
  _type = "vision/face_box"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point top_left
geometry_msgs/Point width_height
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['top_left','width_height']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       top_left,width_height

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(face_box, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.top_left is None:
        self.top_left = geometry_msgs.msg.Point()
      if self.width_height is None:
        self.width_height = geometry_msgs.msg.Point()
    else:
      self.top_left = geometry_msgs.msg.Point()
      self.width_height = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.top_left.x, _x.top_left.y, _x.top_left.z, _x.width_height.x, _x.width_height.y, _x.width_height.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.top_left is None:
        self.top_left = geometry_msgs.msg.Point()
      if self.width_height is None:
        self.width_height = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.top_left.x, _x.top_left.y, _x.top_left.z, _x.width_height.x, _x.width_height.y, _x.width_height.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.top_left.x, _x.top_left.y, _x.top_left.z, _x.width_height.x, _x.width_height.y, _x.width_height.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.top_left is None:
        self.top_left = geometry_msgs.msg.Point()
      if self.width_height is None:
        self.width_height = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.top_left.x, _x.top_left.y, _x.top_left.z, _x.width_height.x, _x.width_height.y, _x.width_height.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
